version: '3.8'
services:
  test-db:
    image: postgres:16
    environment:
      POSTGRES_DB: dawn_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data # In-memory for faster startup 